import { Box } from "@mui/material"
import Head from "next/head"
import { Header } from "src/@core/components"
import * as yup from "yup"

export default function Home() {
  const schema = yup.object().shape({
    email: yup.string().email().required(),
    password: yup.string().required(),
  })

  return (
    <div>
      <Head>
        <title>Admin Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box m="20px">
        <Header title="Dashboard" subtitle="View & monitor all components" />
      </Box>
    </div>
  )
}
